### PR TITLE
feat: Add missing l10n

### PR DESCRIPTION
**Pull request by michaelmairegger**
I think that now everything sould be localized, at least to German

### CODE REVIEW

**Comment by michaelmairegger** [comment]
@nicolaiarocci  should we make the generated resource c# file public instead of internal?

I have some cases where I need the translation of a specific Tabella, e.g. TD24.

**Comment by nicolaiarocci** [comment]
not sure I understand what you mean, but go ahead and make the change, I'll glady review it.

**Comment by michaelmairegger** [comment]
https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/master/Resources/CausalePagamento.Designer.cs#L24 is an internal class because https://github.com/FatturaElettronica/FatturaElettronica.NET/blob/2530ff7ab1a5edf2dc4fcdf6e251ba55f1f2d128/FatturaElettronica.csproj#L35 creates it this way. If we chose PublicResXFileCodeGenerator over ResXFileCodeGenerator, a user of this library is able to use the translated values for the generated .Designer.cs files within his codes.

**Comment by nicolaiarocci** [comment]
oh alright, I see. Go ahead.

**Comment by michaelmairegger** [comment]
Done

**Comment by nicolaiarocci** [comment]
rebased and merged. Released as v3.51, should be up on nuget shortly.

**Pull request closed without merging**
